//users
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT'

//FetchUsers
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

//FetchUsers
export const FETCH_ONE_USER_REQUEST = 'FETCH_ONE_USER_REQUEST'
export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS'
export const FETCH_ONE_USER_ERROR = 'FETCH_ONE_USER_ERROR'
